### ISSUE TITLE
Proxy Endpoint logs IllegalReferenceCountException

### ISSUE THREAD

**Issue by rabeyta** [Nike-Inc/riposte#31]
I believe the downstream service responding immediately and closing connection with an error response without sending the rest of the request is cause of issue.

```
traceId= 2017-03-14T13:30:46,015-07:00 [nioEventLoopGroup-3-1] appname=@@APPNAME@@ environment=@@ENV@@ version=1.0.0.0-SNAPSHOT |-WARN  i.n.channel.DefaultChannelPipeline - An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:50)
	at io.netty.handler.codec.http.DefaultHttpContent.release(DefaultHttpContent.java:72)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.nike.riposte.server.http.impl.RequestInfoImpl.releaseContentChunks(RequestInfoImpl.java:442)
	at com.nike.riposte.server.http.impl.RequestInfoImpl.releaseAllResources(RequestInfoImpl.java:433)
	at com.nike.riposte.server.handler.ChannelPipelineFinalizerHandler.finalizeChannelPipeline(ChannelPipelineFinalizerHandler.java:180)
	at com.nike.riposte.server.handler.ChannelPipelineFinalizerHandler.doChannelRead(ChannelPipelineFinalizerHandler.java:76)
	at com.nike.riposte.server.handler.base.BaseInboundHandlerWithTracingAndMdcSupport.channelRead(BaseInboundHandlerWithTracingAndMdcSupport.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.nike.riposte.server.handler.base.BaseInboundHandlerWithTracingAndMdcSupport.channelRead(BaseInboundHandlerWithTracingAndMdcSupport.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.nike.riposte.server.handler.base.BaseInboundHandlerWithTracingAndMdcSupport.channelRead(BaseInboundHandlerWithTracingAndMdcSupport.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.nike.riposte.server.handler.base.BaseInboundHandlerWithTracingAndMdcSupport.channelRead(BaseInboundHandlerWithTracingAndMdcSupport.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.nike.riposte.server.handler.base.BaseInboundHandlerWithTracingAndMdcSupport.channelRead(BaseInboundHandlerWithTracingAndMdcSupport.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.nike.riposte.server.handler.base.BaseInboundHandlerWithTracingAndMdcSupport.channelRead(BaseInboundHandlerWithTracingAndMdcSupport.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:283)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
	
	
```

**Comment by nicmunroe** [comment]
@rabeyta this should be fixed in Riposte 0.9.3. Closing this issue, but please reopen if you're able to reproduce on the new version.
